name: Github Actions

on:
  push:
    branches: [ "master", "develop/*" ]
  pull_request:
    branches: [ "master", "develop/*" ]

env:
  DOWNSTREAM_REPO: https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/McW-Video/x265_git_downstream.git
  UPSTREAM_REPO: https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/AKILAN-SIVA/x265_git.git
  MASTER_BRANCH: master

jobs:
  Linux-regression-test:
    timeout-minutes: 43200
    runs-on: jaltarang.linux
    steps:
      - name: Preparing workspace
        shell: bash
        run: |
          DOWNSTREAM_DIR="/home/mcw/Akil/x265_regression/x265_git_downstream"
          HARNESS_DIR="/home/mcw/Akil/x265_regression/test-harness-git"

          if [ -d "$DOWNSTREAM_DIR" ]; then
              echo "Downstream repo exists. Deleting..."
              rm -rf "$DOWNSTREAM_DIR"
          fi
          git clone $DOWNSTREAM_REPO "$DOWNSTREAM_DIR"
          cd "$DOWNSTREAM_DIR"
          git checkout "$GITHUB_REF_NAME"

          # test-harness-git
          if [ -d "$HARNESS_DIR" ]; then
              echo "test-harness-git exists. Pulling latest changes..."
              cd "$HARNESS_DIR"
              git pull https://Akilan_Sivakumar:ATATT3xFfGF0dQC-D-7njcKkdJyNco1C_pbPgXDuAITR0s8T2igGU7Izr4EskQ5QeiWuMDuX8bUlLb0tXZ4yltzf60TvtnkpimbeQw_x2XDSpTomsjutMpgIuU6AmokMcsEHJg9Z-7ioHW01xzQH26ma7gRg-OCJI0EDgMLFDAeTiHn8G-t2bbs=AB9EAEFE@bitbucket.org/multicoreware/test-harness-git.git
          else
              echo "Cloning test-harness-git..."
              git clone https://Akilan_Sivakumar:ATATT3xFfGF0dQC-D-7njcKkdJyNco1C_pbPgXDuAITR0s8T2igGU7Izr4EskQ5QeiWuMDuX8bUlLb0tXZ4yltzf60TvtnkpimbeQw_x2XDSpTomsjutMpgIuU6AmokMcsEHJg9Z-7ioHW01xzQH26ma7gRg-OCJI0EDgMLFDAeTiHn8G-t2bbs=AB9EAEFE@bitbucket.org/multicoreware/test-harness-git.git "$HARNESS_DIR"
          fi
      - name: Regression test
        shell: bash
        run: |
          cd /home/mcw/Akil/x265_regression/test-harness-git
          python3 regression-test.py
